### ISSUE TITLE
Installer fails after downloading gpg signature file

### ISSUE THREAD

**Issue by bdimych** [datorrukis/freenet-installer#11]
Linux Mint 19.2,
installer first run:
```
bdimych@freenet-testing:~/freenet-installer/src$
bdimych@freenet-testing:~/freenet-installer/src$ freenet_installer
This is freenet installer, it will download freenet and install it as a background service.
installer_cache (default: /home/bdimych/freenet/distrib):
installation_path (default: /home/bdimych/freenet/install):
nodename (default: None):
language (default: None):
bandwidthlimit_up (default: 15360):
bandwidthdatalimit (default: None):
bandwidthlimit_down (default: -1):
autoupdate (default: y, choices: y, n, true, false): n
upnp (default: y, choices: y, n, true, false): n
physical_security (default: NORMAL, choices: LOW, NORMAL, HIGH, MAXIMUM):
network_security (default: LOW, choices: LOW, NORMAL, HIGH, MAXIMUM):
percentage of freespace in % or GB (freespace: 15.45 G) (default: -1): 10
everything is ready, start installation (default: n, choices: y, n, true, false): y
Download https://github.com/freenet/fred/releases/download/build01484/new_installer_offline_1484.jar
Download https://github.com/freenet/fred/releases/download/build01484/new_installer_offline_1484.jar.sig
Traceback (most recent call last):
  File "/usr/local/bin/freenet_installer", line 11, in <module>
    load_entry_point('freenet-installer==0.0.7', 'console_scripts', 'freenet_installer')()
  File "/usr/local/lib/python3.6/dist-packages/freenet_installer-0.0.7-py3.6.egg/freenet_installer/freenet_installer.py", line 216, in main
    redownload=args.force_download, check_sig=not args.nochecksig)
  File "/usr/local/lib/python3.6/dist-packages/freenet_installer-0.0.7-py3.6.egg/freenet_installer/downloader.py", line 43, in download_installer
    cli = GPG_client()
  File "/usr/local/lib/python3.6/dist-packages/freenet_installer-0.0.7-py3.6.egg/freenet_installer/downloader.py", line 65, in __init__
    self.gpg = gnupg.GPG(gnupghome=self.gpghomedir)
  File "/usr/local/lib/python3.6/dist-packages/python_gnupg-0.4.5-py3.6.egg/gnupg.py", line 818, in __init__
    raise ValueError('gnupghome should be a directory (it isn\'t): %s' % gnupghome)
ValueError: gnupghome should be a directory (it isn't): /home/bdimych/.gpg_dir_freenet_installer
bdimych@freenet-testing:~/freenet-installer/src$
```

**Comment by datorrukis** [comment]
fixed
