### ISSUE TITLE
test on ubuntu 18.04

### ISSUE THREAD

**Issue by datorrukis** [datorrukis/freenet-installer#8]

**Comment by datorrukis** [comment]
TBT
ubuntu 18.04
ubuntu 16.04
centos 
debian

**Comment by devalexk** [comment]
We tested script on Ubuntu 18.04 TLS. Script doesn't work.
```
admin@developeroct-MS-7793:~$ freenet_installer
This is freenet installer, it will download freenet and install it as a background service.
installer_cache (default: /home/admin/freenet/distrib): 
installation_path (default: /home/admin/freenet/install): 
nodename (default: None): 
language (default: None): 
bandwidthlimit_up (default: 15360): 
bandwidthdatalimit (default: None): 
bandwidthlimit_down (default: -1): 
autoupdate (default: y, choices: y, n, true, false): 
upnp (default: y, choices: y, n, true, false): 
physical_security (default: NORMAL, choices: LOW, NORMAL, HIGH, MAXIMUM): 
network_security (default: LOW, choices: LOW, NORMAL, HIGH, MAXIMUM): 
percentage of freespace in % or GB (freespace: 55.86 G) (default: -1): 
everything is ready, start installation (default: n, choices: y, n, true, false): 
install canceled
```
When I launched script in admin mode: 
```
root@developeroct-MS-7793:~# freenet_installer
This is freenet installer, it will download freenet and install it as a background service.
installer_cache (default: /home/admin/freenet/distrib): 
installation_path (default: /home/admin/freenet/install): 
nodename (default: None): 
language (default: None): 
bandwidthlimit_up (default: 15360): 
bandwidthdatalimit (default: None): 
bandwidthlimit_down (default: -1): 
autoupdate (default: y, choices: y, n, true, false): 
upnp (default: y, choices: y, n, true, false): 
physical_security (default: NORMAL, choices: LOW, NORMAL, HIGH, MAXIMUM): 
network_security (default: LOW, choices: LOW, NORMAL, HIGH, MAXIMUM): 
percentage of freespace in % or GB (freespace: 55.86 G) (default: -1): 
everything is ready, start installation (default: n, choices: y, n, true, false): y
checking signature
signature: OK
['/usr/bin/java', '-jar', '/home/admin/freenet/distrib/new_installer_offline.jar', '-console']
Select target path [/home/admin]
press 1 to continue, 2 to quit, 3 to redisplay
[ Starting to unpack ]
[ Processing package: Base (1/3) ]
[ Processing package: License (2/3) ]
[ Processing package: Unix (3/3) ]
[ Unpacking finished ]
[ Starting processing ]
Starting process Setting up the environment (1/16)
The installer isn\'t meant to be run as root
Starting process Setting the Updater up (2/16)
Do not run this script as root.
Do not run this script as root.
Traceback (most recent call last):
  File "/usr/local/bin/freenet_installer", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/freenet_installer/freenet_installer.py", line 221, in main
    install(args)
  File "/usr/local/lib/python3.6/dist-packages/freenet_installer/freenet_installer.py", line 161, in install
    run_freenet(args.installation_path, return_when_init=True)
  File "/usr/local/lib/python3.6/dist-packages/freenet_installer/process.py", line 68, in run_freenet
    loop.run_until_complete(run(RUNNER(install_path), [cmd]))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 473, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/freenet_installer/process.py", line 65, in run
    await k2
UnboundLocalError: local variable 'k2' referenced before assignment
```
Does script work on Ubuntu 18.04 TLS ?

**Comment by datorrukis** [comment]
This works on ubuntu 18.04.
The freenet install cannot be launched as root.
the first issue is a signature issue, 
I ll check that this is still working

**Comment by datorrukis** [comment]
signature still works, may be you had a problem during download,
try with 
```
freenet_installer -U
freenet_installer --force-download -D
```

**Comment by devalexk** [comment]
I tried  freenet_installer -U
```
admin@developeroct-MS-7793:~$ freenet_installer -U
freenet_installer did not found any running instance, cron or installation directory. Nothing to do.
```
If I tried freenet_installer --force-download -D
```
admin@developeroct-MS-7793:~$ freenet_installer --force-download -D
This is freenet installer, it will download freenet and install it as a background service.
Download https://github.com/freenet/fred/releases/download/build01484/new_installer_offline_1484.jar
Traceback (most recent call last):
  File "/usr/local/bin/freenet_installer", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/freenet_installer/freenet_installer.py", line 213, in main
    redownload=args.force_download)
  File "/usr/local/lib/python3.6/dist-packages/freenet_installer/downloader.py", line 39, in download_installer
    download_file(url, installer_file)
  File "/usr/local/lib/python3.6/dist-packages/freenet_installer/downloader.py", line 85, in download_file
    with open(output_file, 'wb') as f:
PermissionError: [Errno 13] Permission denied: '/home/admin/freenet/distrib/new_installer_offline.jar'
```
What did I do wrong?

**Comment by datorrukis** [comment]
as you run the freenet installer with the root user, you cannot delete /home/admin/freenet/distrib/new_installer_offline.jar with your user
run
`sudo chown admin:admin -R /home/admin/freenet/`
to set the ownership of the files and sub-directories to admin.
then 
`freenet_installer --force-download -D`

**Comment by datorrukis** [comment]
I updated to 0.0.6 so i suggest that you run as well 
`pip install --upgrade freenet_installer`

**Comment by devalexk** [comment]
It doesn't work. I deleted freenet folder on my disk. And tried to run commands. Can you give me advice?

```
admin@developeroct-MS-7793:~$ pip -V
pip 19.1.1 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)
```
```
admin@developeroct-MS-7793:~$ pip install --upgrade freenet_installer
Requirement already up-to-date: freenet_installer in /usr/local/lib/python3.6/dist-packages (0.0.6)
Requirement already satisfied, skipping upgrade: psutil in /usr/local/lib/python3.6/dist-packages (from freenet_installer) (5.6.3)
Requirement already satisfied, skipping upgrade: GitPython in /usr/local/lib/python3.6/dist-packages (from freenet_installer) (2.1.11)
Requirement already satisfied, skipping upgrade: python-crontab in /usr/local/lib/python3.6/dist-packages (from freenet_installer) (2.3.6)
Requirement already satisfied, skipping upgrade: python-gnupg in /usr/local/lib/python3.6/dist-packages (from freenet_installer) (0.4.4)
Requirement already satisfied, skipping upgrade: requests in /usr/lib/python3/dist-packages (from freenet_installer) (2.18.4)
Requirement already satisfied, skipping upgrade: gitdb2>=2.0.0 in /usr/local/lib/python3.6/dist-packages (from GitPython->freenet_installer) (2.0.5)
Requirement already satisfied, skipping upgrade: python-dateutil in /usr/local/lib/python3.6/dist-packages (from python-crontab->freenet_installer) (2.8.0)
Requirement already satisfied, skipping upgrade: smmap2>=2.0.0 in /usr/local/lib/python3.6/dist-packages (from gitdb2>=2.0.0->GitPython->freenet_installer) (2.0.5)
Requirement already satisfied, skipping upgrade: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil->python-crontab->freenet_installer) (1.11.0)
```
```
admin@developeroct-MS-7793:~$ freenet_installer -U
freenet_installer did not found any running instance, cron or installation directory. Nothing to do.
```
```
admin@developeroct-MS-7793:~$ freenet_installer --force-download -D
This is freenet installer, it will download freenet and install it as a background service.
Download https://github.com/freenet/fred/releases/download/build01484/new_installer_offline_1484.jar
Download https://github.com/freenet/fred/releases/download/build01484/new_installer_offline_1484.jar.sig
checking signature
WARNING, SIGNATURE CHECK FAILED!!!
program stop

```
```
admin@developeroct-MS-7793:~$ freenet_installer
This is freenet installer, it will download freenet and install it as a background service.
installer_cache (default: /home/admin/freenet/distrib): 
installation_path (default: /home/admin/freenet/install): 
nodename (default: None): 
language (default: None): 
bandwidthlimit_up (default: 15360): 
bandwidthdatalimit (default: None): 
bandwidthlimit_down (default: -1): 
autoupdate (default: y, choices: y, n, true, false): 
upnp (default: y, choices: y, n, true, false): 
physical_security (default: NORMAL, choices: LOW, NORMAL, HIGH, MAXIMUM): 
network_security (default: LOW, choices: LOW, NORMAL, HIGH, MAXIMUM): 
percentage of freespace in % or GB (freespace: 53.72 G) (default: -1): 
everything is ready, start installation (default: n, choices: y, n, true, false): y
checking signature
WARNING, SIGNATURE CHECK FAILED!!!
program stop
```

**Comment by datorrukis** [comment]
it is good that it fails because of "SIGNATURE CHECK FAILED!!!"
could you run:
```
sha1sum /home/admin/freenet/distrib/new_installer_offline.jar
sha1sum /home/admin/freenet/distrib/new_installer_offline.jar.sig
gpg --version
```

**Comment by devalexk** [comment]
```
admin@developeroct-MS-7793:~$ sha1sum /home/admin/freenet/distrib/new_installer_offline.jar
8d9b6f432f08e425954204e27659ffce9830690e  /home/admin/freenet/distrib/new_installer_offline.jar
```
```
admin@developeroct-MS-7793:~$ sha1sum /home/admin/freenet/distrib/new_installer_offline.jar.sig
ae829f000a7793941103db499dde3642fb3c461c  /home/admin/freenet/distrib/new_installer_offline.jar.sig
```
```
admin@developeroct-MS-7793:~$ gpg --version
gpg (GnuPG) 2.2.4
libgcrypt 1.8.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /home/admin/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```
```
admin@developeroct-MS-7793:~$ freenet_installer
This is freenet installer, it will download freenet and install it as a background service.
installer_cache (default: /home/admin/freenet/distrib): 
installation_path (default: /home/admin/freenet/install): 
nodename (default: None): 
language (default: None): 
bandwidthlimit_up (default: 15360): 
bandwidthdatalimit (default: None): 
bandwidthlimit_down (default: -1): 
autoupdate (default: y, choices: y, n, true, false): 
upnp (default: y, choices: y, n, true, false): 
physical_security (default: NORMAL, choices: LOW, NORMAL, HIGH, MAXIMUM): 
network_security (default: LOW, choices: LOW, NORMAL, HIGH, MAXIMUM): 
percentage of freespace in % or GB (freespace: 53.73 G) (default: -1): 
everything is ready, start installation (default: n, choices: y, n, true, false): y
checking signature
WARNING, SIGNATURE CHECK FAILED!!!
program stop
```

**Comment by datorrukis** [comment]
Thank you, I found the issue and I resolve it in the 0.0.7 version. please do 
`pip install --upgrade freenet_installer`

**Comment by devalexk** [comment]
It works properly on Ubuntu 18.04
