### ISSUE TITLE
Instruction from README doesn't work for Ubuntu 16.04.4

### ISSUE THREAD

**Issue by bdimych** [datorrukis/freenet-installer#9]
clean just installed Ubuntu-16.04.4-Desktop,

(by some reasons I didn't do "apt upgrade" as recommended for new installation,
maybe with upgrade these errors will disappear - then just close this issue)

```
bdimych@test1-u16044-64:~/freenet-installer/src$
bdimych@test1-u16044-64:~/freenet-installer/src$ history
    1  git <========== git is not installed by default - could be mentioned in README
    2  sudo apt update
    3  sudo apt install git
    4  git clone https://github.com/datorrukis/freenet-installer.git
    5  cd freenet-installer/
    6  cat README.md
    7  sudo apt-get install openjdk-8-jre python3 cron git gnupg2
    8  cat README.md
    9  cd src                   <========== first method from README
   10  python3 setup.py install <========== gives error "ImportError: No module named 'setuptools'"
   11  sudo apt-get install python3-requests  python3-git python3-gnupg python3-crontab python3-psutil <========== second method
   12  python3 setup.py install <========== gives the same error
   13  sudo apt-get install python3-setuptools <========== should be mentioned
   14  python3 setup.py install <========== error (*)
   15  sudo python3 setup.py install <========== sudo helped
   16  cat ../README.md
   17  freenet_installer <========== error (**) - here sudo is not appropriate - freenet should be installed under regular user
   18  history
bdimych@test1-u16044-64:~/freenet-installer/src$
bdimych@test1-u16044-64:~/freenet-installer/src$


--------------- error (*): ---------------

bdimych@test1-u16044-64:~/freenet-installer/src$
bdimych@test1-u16044-64:~/freenet-installer/src$ python3 setup.py install
running install
Checking .pth file support in /usr/local/lib/python3.5/dist-packages/
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

		[Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/test-easy-install-10043.pth'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

		/usr/local/lib/python3.5/dist-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

	https://pythonhosted.org/setuptools/easy_install.html

Please make the appropriate changes for your system and try again.

bdimych@test1-u16044-64:~/freenet-installer/src$
bdimych@test1-u16044-64:~/freenet-installer/src$


--------------- error (**): ---------------

bdimych@test1-u16044-64:~/freenet-installer/src$
bdimych@test1-u16044-64:~/freenet-installer/src$
bdimych@test1-u16044-64:~/freenet-installer/src$ freenet_installer
This is freenet installer, it will download freenet and install it as a background service.
installer_cache (default: /home/bdimych/freenet/distrib):
installation_path (default: /home/bdimych/freenet/install):
nodename (default: None):
language (default: None):
bandwidthlimit_up (default: 15360):
bandwidthdatalimit (default: None):
bandwidthlimit_down (default: -1):
autoupdate (default: y, choices: y, n, true, false): n
upnp (default: y, choices: y, n, true, false): n
physical_security (default: NORMAL, choices: LOW, NORMAL, HIGH, MAXIMUM):
network_security (default: LOW, choices: LOW, NORMAL, HIGH, MAXIMUM):
percentage of freespace in % or GB (freespace: 4.98 G) (default: -1): 3 <========== ??? confusing phrase and default value ???
everything is ready, start installation (default: n, choices: y, n, true, false): y
Download https://github.com/freenet/fred/releases/download/build01484/new_installer_offline_1484.jar
Download https://github.com/freenet/fred/releases/download/build01484/new_installer_offline_1484.jar.sig
Traceback (most recent call last):
  File "/usr/local/bin/freenet_installer", line 9, in <module>
    load_entry_point('freenet-installer==0.0.6', 'console_scripts', 'freenet_installer')()
  File "/usr/local/lib/python3.5/dist-packages/freenet_installer-0.0.6-py3.5.egg/freenet_installer/freenet_installer.py", line 210, in main
    redownload=args.force_download)
  File "/usr/local/lib/python3.5/dist-packages/freenet_installer-0.0.6-py3.5.egg/freenet_installer/downloader.py", line 43, in download_installer
    cli = GPG_client()
  File "/usr/local/lib/python3.5/dist-packages/freenet_installer-0.0.6-py3.5.egg/freenet_installer/downloader.py", line 62, in __init__
    self.gpg = gnupg.GPG(gnupghome=self.gpghomedir)
  File "/usr/lib/python3/dist-packages/gnupg.py", line 735, in __init__
    os.makedirs(self.gnupghome,0x1C0)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/freenet_installer-0.0.6-py3.5.egg/freenet_installer/gpg_dir'
bdimych@test1-u16044-64:~/freenet-installer/src$
bdimych@test1-u16044-64:~/freenet-installer/src$

```

**Comment by datorrukis** [comment]
I updated the README, it should work now, you have to choose one way to install freenet_installer globally/virtualenv, git/pip making 4 different way to install it.

**Comment by bdimych** [comment]
Linux Mint 19.2:
first method "sudo python3 setup.py install" - works fine,

second method "sudo pip3 install freenet_installer" - gives error "ModuleNotFoundError: No module named 'setuptools'",
to fix - just install python3-setuptools,
please append it to the apt-get command,

and I think the bug can be closed,
virtualenv methods 3 and 4 - I just don't want to check,
for me global installation looks sufficient,

**Comment by datorrukis** [comment]
Done
